# Day 01 - Task 03
# Import an external module and use it

import lorem;
myParagraph = lorem.paragraph();

# this is going to output the generated by the 'paragraph' method 
print(myParagraph + "\n");

# this print statment will directly output the return value of 'paragraph()' method
print(lorem.paragraph());
